### ISSUE TITLE
NoResp! with dial / hand wheel

### ISSUE THREAD

**Issue by HorstBaerbel** [heise/MaXYposi_Grbl_644#21]
The control panel works fine for me (including jogging all axes via the "joystick" buttons), except for the dial / hand wheel. If I turn it even just one step I instantly get "NoResp!" on the display and the control panel locks up. I have to press "Reset" to activate it again. What could be wrong?
EDIT: I turned on "debug_jog" in jogpad.c and get "ALARM:1" when I turn the hand wheel.

**Comment by feistus** [comment]
I can confirm that issue, happens when $5=1. 
When I set $5=0, handwheel works.

**Comment by danst0** [comment]
Still ALARM:1 with $5=0;-(

**Comment by pheowl** [comment]
I can confirm the issue, happens for both, $5=1 and $5=0,
also found the cause/solution:
If the c axis is enabled and NC switches are used, the c axis is also inverted and is therefore always "triggered". If all switches are NO, then this issue should not be present.
To solve the issue (I use NO switches and $5=1) I just shorted the GND pin and C axis limit switch. When I do this, the dial works perfectly.
Another approach might be to not use $5=1 but use the pin invert mask in the config.h. I have not tested this however.

I hope this helps

EDIT:
The relevant piece of code is in the limit.c:
 ```
 ISR(LIMIT_INT_vect) {
	#ifdef DIAL_ENABLED
    // first check Encoder Wheel on same pins
    check_encoder_hook(LIMIT_PIN);
     if (!limits_get_state()) return; // no limit pins envolved   **this returns 0 if not all (incl. C axis) switches are closed/opened**
	#endif
    if (!(WDTCSR & (1<<WDIE))) { WDTCSR |= (1<<WDIE); } 
 }
 ```

**Comment by HorstBaerbel** [comment]
Thanks for the hint! I can't remember if I enabled or disabled C-axis support. Did you try if this happens with the C-axis disabled too?

**Comment by pheowl** [comment]
Sorry for the delay, I did not test this, but I guess it will give the same result since there is no ifdef in the cpu_map.h where the limit mask is defined:
```
#define LIMIT_MASK ((1<<X_LIMIT_BIT)|(1<<Y_LIMIT_BIT)|(1<<Z_LIMIT_BIT)|(1<<C_LIMIT_BIT)) // All limit bits
```
Adding an ifdef here and removing C_LIMIT_BIT should fix the issue hopefully. I will test this if I have some spare time and do not need the machine for a day.

**Comment by HorstBaerbel** [comment]
The last solution did not work for me. I inserted the ifdef and removed C_LIMIT_BIT from LIMIT_MASK, but I still get the "NoResp!" message... :'/
EDIT: Damn. I do not have the machine connected atm, so this can't work. I'll try it again when I reassembled everything...
